name: PolyQuant cmake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install nlohmann-json-dev
      run: |
          sudo apt-get install nlohmann-json-dev 

    - name: Install libh5cpp
      run: |
          curl http://repos.pni-hdri.de/debian_repo.pub.gpg | apt-key add - 
          cd /etc/apt/sources.list.d 
          sudo wget http://repos.pni-hdri.de/buster-pni-hdri.list
          sudo apt-get update
          sudo apt-get install libh5cpp0.4.0 libh5cpp0.4.0-dbg libh5cpp0.4.0-doc libh5cpp0.4.0-dev

    - name: Install libint
      run: |
          git clone git@github.com:evaleev/libint.git
          cd libint
          ./configure \
            --enable-eri=1 \
            --enable-eri2=1 \
            --enable-eri3=1 \
            --enable-fma=0 \
            --with-max-am=5 \
            --with-eri-max-am=5,4 \
            --with-eri2-max-am=7,6 \
            --with-eri3-max-am=7,6 \
            --with-opt-am=3 \
            --with-cartgauss-ordering=gamess
          make export
          tar xzf libint-2.7.0-beta.6.tgz
          cd libint-2.7.0-beta.6
          cmake . \
               -DCMAKE_CXX_COMPILER=g++ \
               -Denable-fortran=ON \
               -DLIBINT2_SHGAUSS_ORDERING=gaussian \
               -DLIBINT2_REALTYPE=double
          cmake --build .
          cmake --build . --target install

    - name: Create Build Environment
      run: |
          cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DPOLYQUANT_DEBUG=0 -DPOLYQUANT_DOC=0 -DPOLYQUANT_TEST=1 -DPOLYQUANT_CODE_COVERAGE=1

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
