name: Polyquant clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Optionally generate compile_commands.json

    - uses: ZedThree/clang-tidy-review@v0.7.0
      id: review
    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
